### ISSUE TITLE
Rus version for Believe or Die - A Search for "Ashcan" Pete

### ISSUE THREAD

**Issue by Ssid113** [FASTNAVi/Believe_or_Die_1#4]
Hello @FASTNAVi . If possible, add this translation. Thanks.
[Localization.Russian.txt](https://github.com/FASTNAVi/Believe_or_Die_1/files/3465348/Localization.Russian.txt)

**Comment by Ssid113** [comment]
@FASTNAVi

**Comment by FASTNAVi** [comment]
Hi @Ssid113 , I was for some time offline. Sorry for the late respond.

Thank you for your effort. I will add it right now.

**Comment by Ssid113** [comment]
Thank you.
