### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by vidimus** [FASTNAVi/Believe_or_Die_1#5]
Hello, @FASTNAVi 

I would like to translate into Spanish your scenario. Are you available for updating it?

**Comment by vidimus** [comment]
Hello, @FASTNAVi , I'm still waiting.

**Comment by vidimus** [comment]
Hello, @FASTNAVi 

Did you read my message about the Spanish translation?

**Comment by vidimus** [comment]
Hello, @FASTNAVi ?

**Comment by vidimus** [comment]
@FASTNAVi ???

**Comment by vidimus** [comment]
Nothing yet, @FASTNAVi ?

**Comment by FASTNAVi** [comment]
Hello @vidimus ,
Yes, I would be happy if you will do so. Are you still interested?

I am sorry, for some reason I did not receive any notification from Github.

**Comment by vidimus** [comment]
@FASTNAVi 

Yes, I am, but there're other scenarios taking my time. Anyway, I will contact you better via Discord.

**Comment by vidimus** [comment]
@FASTNAVi  after a long time, I've finished the translation. Now I'm testing it, so it will be ready within a few days.

**Comment by vidimus** [comment]
@FASTNAVi 
Here's the Spanish translation:

[Localization.Spanish.txt](https://github.com/FASTNAVi/Believe_or_Die_1/files/6412276/Localization.Spanish.txt)
