### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by GabroDonuts** [FASTNAVi/Believe_or_Die_1#6]
Hi!! I've translated the scenario in Italian. Hope you could update it as soon as possible :) thank you so much! Gabro
[Localization.Italian.txt](https://github.com/FASTNAVi/Believe_or_Die_1/files/5942076/Localization.Italian.txt)

**Comment by FASTNAVi** [comment]
Hi @GabroDonuts ,

I am back home and finally find time to upload your translation.

Once more, I apology for the delay.

Please check it and let me know if everything works good for you ;-)

Thank you very much for your support!
